#------------------------------------------------------------------------------#
# Causal inference covariate selection
# K Luijken
#
# Execute script to perform a single run of the simulations
#------------------------------------------------------------------------------#

# Some notes on the format of the raw data output
#------------------------------------------------------------------------------#
# For each scenario from datagen_scenarios(), a .rds file with table of output 
# is created. The table contains #method x #rep = 3 x 5000 = 10000 rows, 
# For example:
#Scennum     Seed           Model Method       MRR          MOR   mod.coefs    SE(coefs)                            filepath
#       1 41038673     Unadjusted   <NA>  1.239323     1.507754          NA         ... ./data/results_raw/FLIC_0.157/S1.rds
#       1 41038673           Full   FLIC 0.8809378    0.7632651   0.2610278         ... ./data/results_raw/FLIC_0.157/S1.rds
#       1 41038673 Selected_0.157   FLIC 0.8862254    0.7730111   0.2679882         ... ./data/results_raw/FLIC_0.157/S1.rds

# Load librairies ----
#------------------------------------------------------------------------------#
source(file = "./rcode/packages/packages.R")
source(file = "./rcode/dgm/sim_scen.R")
source(file = "./rcode/dgm/gen_data.R")
source(file = "./rcode/analyses/analyse_data.R")

# Helpers ----
#------------------------------------------------------------------------------#

# Save results in existing rds files (generated by create_dirs.R)
save_results <- function(results){
  filepath <- unique(results[['filepath']])
  
  con <- file(filepath)
  while (isOpen(con)){
    Sys.sleep(2)
  }
  open(con)
  results_in_file <- readRDS(filepath)
  new_results <- rbind(results_in_file, 
                       results)
  rownames(new_results) <- NULL
  saveRDS(new_results, file = filepath)
  close(con)

}

# Generate seeds
get_seeds <- function(rep){
  set.seed(20200501)
  n_seed <- nrow(datagen_scenarios()) * rep 
  seed <- sample(1:1e8, 
                 size = n_seed, 
                 replace = FALSE)
}


# Workhorse simulations ----
#------------------------------------------------------------------------------#

# Run simulation for 1 datagen_scenario and 1 rep
perform_one_run <- function(datagen_scenario,
                            use_analysis_scenarios, seed){
  # Generate data
  data <- gen_data(nobs = datagen_scenario[['nobs']],
                       nL = datagen_scenario[['nL']],
                       bAL1 = datagen_scenario[['bAL1']],
                       bAL2 = datagen_scenario[['bAL2']],
                       bAL3 = datagen_scenario[['bAL3']],
                       bYL1 = datagen_scenario[['bYL1']],
                       bYL2 = datagen_scenario[['bYL2']],
                       bYL3 = datagen_scenario[['bYL3']],
                       Yint = datagen_scenario[['Yint']],
                       sd_UY = datagen_scenario[['sd_UY']],
                       rhoL = datagen_scenario[['rhoL']],
                       seed = seed)
  # Analyse the data using use_analysis_scenarios
  results <- apply(use_analysis_scenarios, 
                   1, 
                   FUN = analyse_data,
                   datagen_scenario = datagen_scenario, 
                   data = data,
                   seed = seed)
  # save results
  lapply(results,
         FUN = save_results)
}

# test, remove this when all works
# perform_one_run(datagen_scenario = datagen_scenarios()[10,],
#                 use_analysis_scenarios = analysis_scenarios(),
#                 seed = 55)


# Repeat 'perform_one_run' rep times, for 1 datagen_scenario 
sim_one_datagen_scenario <- function(datagen_scenario,
                                     use_analysis_scenarios,
                                     rep,
                                     seeds){
  scen_num <- as.numeric(datagen_scenario['scen_num'])
  for(i in 1:rep){
    seed = seeds[(rep * scen_num + i)]
    perform_one_run(datagen_scenario = datagen_scenario,
                    use_analysis_scenarios = use_analysis_scenarios,
                    seed = seed)
  message("Done with scenario ", scen_num, " and replication ", i)
  }
}

# test, remove this when all works
# sim_one_datagen_scenario(datagen_scenario = datagen_scenarios()[5,],
#                          use_analysis_scenarios = analysis_scenarios(),
#                          rep = 2,
#                          seeds = get_seeds(rep=2))


# Function to run overall simulations.
# For each of the datagen_scenarios(), rep  data sets will be generated and 
# analysed using methods analysis_scenarios().  

run_sim <- function(rep, 
                    use_datagen_scenarios,
                    use_analysis_scenarios,
                    seeds){
  invisible(apply(use_datagen_scenarios, 
                  1, 
                  FUN = sim_one_datagen_scenario, 
                  use_analysis_scenarios = use_analysis_scenarios,
                  rep = rep,
                  seeds = seeds))
}

# test, remove this when all works
# run_sim(rep = 100, 
#         use_datagen_scenarios = datagen_scenarios()[c(1:10),],
#         use_analysis_scenarios = analysis_scenarios(),
#         seeds = get_seeds(rep = 100))

